services:
  octoprint:
    environment:
      - ENABLE_MJPG_STREAMER=true # Used to enable the camera streaming
      - CAMERA_DEV=/dev/video4 # Camera device on /dev
    image: octoprint/octoprint:latest
    device_cgroup_rules: # Used to enable hot-plug
      - c 188:0 rmw # Serial USB
      - c 81:* rmw # Camera
    restart: unless-stopped
    volumes:
      - octoprint:/octoprint
      - /dev:/dev
    ports:
      - 80:80

  weston:
    image: torizon/weston-vivante:${CT_TAG_WESTON_VIVANTE}
    container_name: weston
    environment:
      - ACCEPT_FSL_EULA=1
    restart: unless-stopped
    depends_on:
      - octoprint
    network_mode: host
    cap_add:
      - CAP_SYS_TTY_CONFIG
    volumes:
      - /dev:/dev
      - /tmp:/tmp
      - /run/udev/:/run/udev/
    device_cgroup_rules:
      - 'c 4:* rmw'
      - 'c 13:* rmw'
      - 'c 199:* rmw'
      - 'c 226:* rmw'
    command: --developer --tty=/dev/tty7

  chromium:
    image: torizon/chromium:${CT_TAG_CHROMIUM}
    container_name: chromium
    restart: unless-stopped
    depends_on:
      - weston
      - octoprint
    volumes:
      - /tmp:/tmp
      - /var/run/dbus:/var/run/dbus
      - /dev/galcore:/dev/galcore
    device_cgroup_rules:
      - 'c 199:* rmw'
    security_opt:
      - seccomp=unconfined
    shm_size: '256mb'
    command: --window-size=800,480  http://10.22.1.51/#control

volumes:
  octoprint:
